# mappings

porosity_mapping = {
    # BRO soil types
    "grindNietGespecificeerd": "Gravel",
    "grondNietGespecificeerd": None,
    "kleiigZand": "Clayey Sands",
    "matigSiltigZand": "Silty Sands",
    "matigSiltigeKlei": "Clay/Silty Clay/Sandy Clay; Low Plasticity",
    "matigZandigGrind": "Sand/Gravelly Sand",
    "matigZandigeKlei": "Silty Clay/Sandy Clay",
    "mineraalarmVeen": "Organic Silt/Silty Clay; Low Plasticity",
    "sterkKleiigVeen": "Organic Clay; High Plasticity",
    "sterkSiltigZand": "Silty Sands",
    "sterkSiltigeKlei": "Clay/Silty Clay/Sandy Clay; Low Plasticity",
    "sterkZandigGrind": "Sand/Gravelly Sand",
    "sterkZandigVeen": "Sand; Fine",
    "sterkZandigeKlei": "Silty Clay/Sandy Clay",
    "sterkZandigeLeem": "Silty Clay/Sandy Clay",
    "uiterstSiltigZand": "Silty Sands",
    "uiterstSiltigeKlei": "Clay/Silty Clay/Sandy Clay; Low Plasticity",
    "uiterstZandigGrind": "Sand/Gravelly Sand",
    "zandNietGespecificeerd": "Sand; Coarse",
    "zwakKleiigVeen": "Organic Silt/Silty Clay; Low Plasticity",
    "zwakSiltigZand": "Silty Sands",
    "zwakSiltigeKlei": "Clay/Silty Clay/Sandy Clay; Low Plasticity",
    "zwakZandigGrind": "Sand/Gravelly Sand",
    "zwakZandigVeen": "Organic Silt/Silty Clay; Low Plasticity",
    "zwakZandigeKlei": "Silty Clay/Sandy Clay",
    "zwakZandigeLeem": "Organic Silt/Silty Clay; Low Plasticity",

    # GeoTOP soil types
    "zand fijn": "Sand; Fine",
    "zand midden": "Sand/Gravelly Sand; Well Graded; Little to No Fines",
    "zand grof": "Sand; Coarse",
    "kleiig zand, zandige klei en leem": "Silty Clay/Sandy Clay",
    
    # Source soil types
    "coarse sand": "Sand; Coarse",
    "Poorly graded silty fine sand": "Silty Sands",
    "Dry sand": "Sand; Coarse",
    "Light sandy soil": "Sand; Coarse",
    "Coarse sand/gravel": "Sand; Coarse",
    "matig vast fijn zand": "Sand; Fine",
    "Fine sand, medium compacted": "Sand; Fine",
    "matig tot fijn zand": "Sand; Fine",
    "fijn zand, soms sterk siltig": "Silty Sands",
    "fijn zand, soms siltig": "Silty Sands",
    "fijn zand": "Sand; Fine",
    "middelfijn zand": "Sand; Fine",
    "fijn tot middelfijn zand (zeer uniform)": "Sand; Fine",
    "fijn tot middelfijn zand, soms siltig": "Silty Sands",
    "fijn tot middelfijn zand": "Sand; Fine",
    "Quicksand and gravel": "Sand/Gravelly Sand",
    "Gravel, fines, boulders": "Sand/Gravelly Sand",
    "Sand and boulders": "Sand/Gravelly Sand",
    "founded on gravel with horizontal creep in silt": "Gravel/Silty Sandy Gravel",
    "Hard material, probably pan": "Sand/Gravelly Sand",
    "Unknown, probably fine": "Sand; Fine",
    
    # other
    "Moderately fine sand": "Sand; Fine",
    "Coarse sand": "Sand; Coarse",
    "Fine sand": "Sand; Fine",
    
}


friction_angle_mapping = {
    # BRO data
    "grindNietGespecificeerd": "Well graded gravel, sandy gravel, with little or no fines",
    "grondNietGespecificeerd": None,
    "kleiNietGespecificeerd": "Clayey sands",
    "kleiigZand": "Clayey sands",
    "matigSiltigZand": "Silty sands",
    "matigSiltigeKlei": "Clayey silts - compacted",
    "matigZandigGrind": "Well graded gravel, sandy gravel, with little or no fines",
    "matigZandigeKlei": "Clayey sands",
    "mineraalarmVeen": "Loam",
    #"sterkKleiigVeen": "Clay",
    "sterkSiltigZand": "Silty sands",
    "sterkSiltigeKlei":  "Silty clay",
    "sterkZandigGrind": "Well graded gravel, sandy gravel, with little or no fines",
    "sterkZandigVeen": "Sand",
    "sterkZandigeKlei": "Clayey sands",
    "sterkZandigeLeem": "Loam",
    "uiterstSiltigZand": "Silty sands",
    "uiterstSiltigeKlei": "Clayey sands",
    "uiterstZandigGrind": "Well graded gravel, sandy gravel, with little or no fines",
    "veenNietGespecificeerd": "Peat and other highly organic soils",
    "zandNietGespecificeerd": "Sand",
    "zwakKleiigVeen": "Silty clay",
    "zwakSiltigZand": "Silty sand",
    "zwakSiltigeKlei": "Silty clay",
    "zwakZandigGrind": "Poorly graded gravel, sandy gravel, with little or no fines",
    "zwakZandigVeen": "Loamy sand, sandy clay Loam",
    "zwakZandigeKlei": "Clayey sands",
    "zwakZandigeLeem": "Loamy sand, sandy clay Loam",
    
    # GeoTOP data
    "zand fijn": "Sand",
    "zand midden": "Sand",
    "zand grof": "Sand",
    "kleiig zand, zandige klei en leem": "Clayey sands",
    
    #Source data
    "coarse sand": "Sand",  
    "Poorly graded silty fine sand": "Silty sands",  
    "Dry sand": "Sand",  
    "Light sandy soil": "Sand",  
    "Coarse sand/gravel": "Well graded sands, gravelly sands, with little or no fines",
    "matig vast fijn zand": "Medium sand",  
    "Fine sand, medium compacted": "Medium sand",  
    "matig tot fijn zand": "Medium sand",  
    "fijn zand, soms sterk siltig": "Silty sands",  
    "fijn zand, soms siltig": "Silty sands",  
    "fijn zand": "Sand",  
    "middelfijn zand": "Sand",  
    "fijn tot middelfijn zand (zeer uniform)": "Poorly graded clean sand - Compacted",  
    "fijn tot middelfijn zand, soms siltig": "Silty sands",  
    "fijn tot middelfijn zand": "Sand",  
    "Quicksand and gravel": "Silty gravels, silty sandy gravels",  
    "Gravel, fines, boulders": "Clayey gravels, clayey sandy gravels",  
    "Sand and boulders": "Sandy gravels - Loose",  
    "founded on gravel with horizontal creep in silt": "Silty gravels, silty sandy gravels",  
    "Hard material, probably pan": "Well graded gravel, sandy gravel, with little or no fines",  
    "Unknown, probably fine": "Sand",
    
    #other
    "Moderately fine sand": "Sand",
    "Coarse sand": "Sand",
    "Fine sand": "Sand"
}


hydraulic_conductivity_mapping = {
    # BRO data
    "grindNietGespecificeerd": "Gravel",
    "grondNietGespecificeerd": None,
    #"kleiNietGespecificeerd": "Clay",
    "kleiigZand": "Clayey Sand",
    "matigSiltigZand": "Silty Sand",
    "matigSiltigeKlei": "Inorganic Clay/Silty Clay/Sandy Clay; Low Plasticity",
    "matigZandigGrind": "Sandy Gravel",
    "matigZandigeKlei": "Inorganic Clay/Silty Clay/Sandy Clay; Low Plasticity",
    "mineraalarmVeen": "Organic Clay/Silty Clay; Low Plasticity",  # No peat or organic soil type
    "sterkKleiigVeen": "Organic Clay/Silty Clay; Low Plasticity",
    "sterkSiltigZand": "Silty Sand",
    "sterkSiltigeKlei": "Inorganic Clay/Silty Clay/Sandy Clay; Low Plasticity",
    "sterkZandigGrind": "Sandy Gravel",
    "sterkZandigVeen": "Organic Clay/Silty Clay; Low Plasticity",
    "sterkZandigeKlei": "Clayey Sand",
    "sterkZandigeLeem": "Organic Clay/Silty Clay; Low Plasticity",
    "uiterstSiltigZand": "Silty Sand",
    "uiterstSiltigeKlei": "Inorganic Silty Fine Sand/Clayey Fine Sand; Slight Plasticity",
    "uiterstZandigGrind": "Sandy Gravel",
    "veenNietGespecificeerd": "Organic Clay/Silty Clay; Low Plasticity",
    "zandNietGespecificeerd": "Medium Sand",
    "zwakKleiigVeen": "Organic Clay/Silty Clay; Low Plasticity",
    "zwakSiltigZand": "Silty Sand",
    #"zwakSiltigeKlei": "Clay",
    "zwakZandigGrind": "Sand/Gravelly Sand; Poorly Graded; Little to No Fines",
    "zwakZandigVeen": "Organic Clay/Silty Clay; Low Plasticity",
    #"zwakZandigeKlei": "Clay",
    "zwakZandigeLeem": "Organic Clay/Silty Clay; Low Plasticity",
    
    # source data
    "coarse sand": "Coarse Sand",
    "Poorly graded silty fine sand": "Inorganic Silty Fine Sand/Clayey Fine Sand; Slight Plasticity",
    "Dry sand": "Medium Sand",
    "Light sandy soil": "Medium Sand",
    "Coarse sand/gravel": "Coarse Sand",
    "matig vast fijn zand": "Fine Sand", 
    "Fine sand, medium compacted": "Fine Sand",
    "matig tot fijn zand": "Medium Sand",
    "fijn zand, soms sterk siltig": "Inorganic Silty Fine Sand/Clayey Fine Sand; Slight Plasticity",
    "fijn zand, soms siltig": "Inorganic Silty Fine Sand/Clayey Fine Sand; Slight Plasticity",
    "fijn zand": "Fine Sand",
    "middelfijn zand": "Medium Sand",
    "fijn tot middelfijn zand (zeer uniform)": "Fine Sand",
    "fijn tot middelfijn zand, soms siltig": "Inorganic Silty Fine Sand/Clayey Fine Sand; Slight Plasticity",
    "fijn tot middelfijn zand": "Fine Sand",
    "Quicksand and gravel": "Silty Gravel/Silty Sandy Gravel",
    "Gravel, fines, boulders": "Silty Gravel/Silty Sandy Gravel",
    "Sand and boulders": "Sand/Gravel; Well Graded; No fines",
    "founded on gravel with horizontal creep in silt": "Silty Gravel/Silty Sandy Gravel",
    "Hard material, probably pan": "Coarse Sand",
    "Unknown, probably fine": "Silty Sand",
    
    # GeoTOP data
    "zand fijn": "Fine Sand",
    "zand midden": "Medium Sand",
    "zand grof": "Coarse Sand",
    "kleiig zand, zandige klei en leem": "Clayey Sand",
        
    # other
    "Moderately fine sand": "Medium Sand",
    "Coarse sand": "Coarse Sand",
    "Fine sand": "Fine sand"
    
}


particle_size_mapping = {
    # BRO data
    "matigSiltigZand": "Silty sand",
    "sterkSiltigZand": "Silty sand",
    "zwakSiltigZand": "Silty sand",
    "zandNietGespecificeerd": "Sand",
    "zwakZandigGrind": "Gravel",
    "matigZandigGrind": "Gravel",
    "sterkZandigGrind": "Gravel",
    "uiterstZandigGrind": "Gravel",
    "kleiigZand": "Clayey sand",
    "matigZandigeKlei": "Clayey sand",
    "sterkZandigeKlei": "Clayey sand",
    "zwakZandigeKlei": "Clayey sand",
    "matigSiltigeKlei": "Clayey silt",
    "sterkSiltigeKlei": "Clayey silt",
    "zwakSiltigeKlei": "Clayey silt",
    "uiterstSiltigeKlei": "Clayey silt",
    "mineraalarmVeen": "Peat",
    "veenNietGespecificeerd": "Peat",
    "sterkKleiigVeen": "Peat",
    "zwakKleiigVeen": "Peat",
    "zwakZandigVeen": "Peat",
    "sterkZandigVeen": "Peat",
    "grondNietGespecificeerd": None,
    "grindNietGespecificeerd": "Gravel",
    "N/A": None,
    "uiterstSiltigZand": "Silty sand",
    "sterkZandigeLeem": "Clayey silt",
    "kleiNietGespecificeerd": "Clayey sand",
    "zwakZandigeLeem": "Clayey silt",
    
    # source data
    "coarse sand": "Coarse sand",
    "Poorly graded silty fine sand": "Fine sand",
    "Dry sand": "Medium sand",
    "Light sandy soil": "Medium sand",
    "Coarse sand/gravel": "Coarse sand",
    "matig vast fijn zand": "Fine sand",
    "Fine sand, medium compacted": "Fine sand",
    "matig tot fijn zand": "Medium sand",
    "fijn zand, soms sterk siltig": "Silty sand",
    "fijn zand, soms siltig": "Silty sand",
    "fijn zand": "Fine sand",
    "middelfijn zand": "Medium sand",
    "fijn tot middelfijn zand (zeer uniform)": "Medium sand",
    "fijn tot middelfijn zand, soms siltig": "Silty sand",
    "fijn tot middelfijn zand": "Medium sand",
    "Quicksand and gravel": "Clayey sand",
    "Gravel, fines, boulders": "Clayey sand",
    "Sand and boulders": "Coarse sand",
    "founded on gravel with horizontal creep in silt": "Silty sand",
    "Hard material, probably pan": "Coarse sand",
    "Unknown, probably fine": "Fine sand",
    
    # GeoTOP data
    "zand fijn": "Fine sand",
    "zand midden": "Medium sand",
    "zand grof": "Coarse sand", 
    "kleiig zand, zandige klei en leem": "Clayey sand", 
    
    #other
    "Moderately fine sand": "Medium sand",
    "Coarse sand": "Coarse sand",
    "Fine sand": "Fine sand"
}

